### ISSUE TITLE
Error: Can't find stylesheet to import (splide-core.min)

### ISSUE THREAD

**Issue by mariantanase** [italia/bootstrap-italia-playground#26]
Salve,
Dopo aver aggiornato bootstrap-italia alla versione più recente 2.2.0 :
`npm i bootstrap-italia`

Quando voglio compilare :
`yarn build`

Non va a buon fine, ed esce questo errore :
```
yarn run v1.22.19
$ yarn vercel && sass --load-path=. scss/bootstrap-italia-custom.scss:css/compiled/bootstrap-italia-custom.min.css --style=compressed
$ rm -rf ./bootstrap-italia && cp -r node_modules/bootstrap-italia/ ./bootstrap-italia
Error: Can't find stylesheet to import.
  ╷
2 │ @import '@splidejs/splide/dist/css/splide-core.min';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\bootstrap-italia\src\scss\custom\_carousel.scss 2:9   @import
  node_modules\bootstrap-italia\src\scss\bootstrap-italia.scss 74:9  @import
  scss\bootstrap-italia-custom.scss 11:9                             root stylesheet
error Command failed with exit code 65.
```

Ho riprovato ma non va.
C'è qualche bug ? O sbaglio io ?

Grazie

**Comment by astagi** [comment]
Ciao @mariantanase non saprei davvero, ho provato dall'attuale main a fare

```
yarn build
```

e tutto gira regolarmente.. Prova a cancellare la cartella `node_modules` e reinstallare tutto con `yarn`

**Comment by astagi** [comment]
Ciao di nuovo @mariantanase ho cambiato i comandi anche per far andare Vercel. Pulla pure l'ultima versione e questo punto i comandi diventano

Installazione:

```sh
npm install
```

Build

```sh
npm run build
```

**Comment by mariantanase** [comment]
Ho scaricato il pacchetto e ho eseguito i commandi sopra menzionati. Purtroppo adesso non compila più.```

```
$ npm run build

 bootstrap-italia-playground@2.0.0 build
 npm run vercel && sass --load-path=node_modules scss/bootstrap-italia-custom.scss:css/compiled/bootstrap-italia-custom.min.css --style=compressed

Error: double-loading config "D:\bearsampp12\bin\nodejs\nodejs19.0\etc\npmrc" as "global", previously loaded as "user"
    at [loadObject] (D:\bearsampp12\bin\nodejs\nodejs19.0\node_modules\npm\node_modules\@npmcli\config\lib\index.js:554:13)
    at D:\bearsampp12\bin\nodejs\nodejs19.0\node_modules\npm\node_modules\@npmcli\config\lib\index.js:593:32    at async [loadFile] (D:\bearsampp12\bin\nodejs\nodejs19.0\node_modules\npm\node_modules\@npmcli\config\lib\index.js:592:5)
    at async Config.load (D:\bearsampp12\bin\nodejs\nodejs19.0\node_modules\npm\node_modules\@npmcli\config\lib\index.js:289:5)
    at async #load (D:\bearsampp12\bin\nodejs\nodejs19.0\node_modules\npm\lib\npm.js:213:5)
    at async module.exports (D:\bearsampp12\bin\nodejs\nodejs19.0\node_modules\npm\lib\cli.js:114:5) 
```

E non crea la cartella css/compiled con il file css dentro.
```

**Comment by mariantanase** [comment]
Credo che ho un problema con node della mia LAMP. Utilizzando un'altra , la compilazione avviene correttamente:
```
$ npm run build

 bootstrap-italia-playground@2.0.0 build
 npm run vercel && sass --load-path=node_modules scss/bootstrap-italia-custom.scss:css/compiled/bootstrap-italia-custom.min.css --style=compressed


 bootstrap-italia-playground@2.0.0 vercel
 rm -rf ./bootstrap-italia && cp -r node_modules/bootstrap-italia/ ./bootstrap-italia

```

**Comment by astagi** [comment]
Capisco, son contento sia stato risolto @mariantanase !
